version: '3'

services:
  app:
    image: cryselayala98/practica-docker-node-js:1.0
    # cryselayala98/practica-docker-node-js esta montado en dockerhub
    # build: ./app
    ports:
      - "3000:3000"
    restart: always
    links:
      - mongo
    volumes:
      #- ./app:/usr/src/app
      #- /usr/src/app/node_modules  
      - myremotevolumen/usr/src/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  myremotevolume:
